### ISSUE TITLE
Merchant API documentation should recommend creating the refund with Payment ID in addition to order number

### ISSUE THREAD

**Issue by laurasaari** [paytrail/documentation#11]
**Is your feature request related to a problem? Please describe.**
Currently merchant API refund creation does not mention that also payment id can be used to create refund (not only order number)

This would help merchants who do not use unique order numbers

**Describe the solution you'd like**

In old documentation:

- [4.8.4. Create Refund & 4.8.4.1. Request](https://docs.paytrail.com/en/index-all.html#idm186545394032)

```http
POST /merchant/v1/payments/:orderNumber/refunds
```

Could include example for payment id (returned with E2 payments `PARAMS_OUT[PAYMENT_ID]`). Note also the required header `Refund-Origin`.

```http
POST /merchant/v1/payments/:paymentId/refunds
Refund-Origin: internal
````

**Comment by nikoheikkila** [comment]
Reopening this as @PaytrailTech found out in #57 that this has not been fixed. Will investigate further.
