### ISSUE TITLE
Images in the documentation could do with an update/refresh

### ISSUE THREAD

**Issue by PaytrailTech** [paytrail/documentation#15]
**Is your feature request related to a problem? Please describe.**

Some images, for example in the REST interface documentation payment-json-en.png and other interfaces E1-> Migrating -> payment-form-en.png, could do with an update. They look oldish (the server is represented by an ancient desktop mein unit for example) and do not fit with the style of the documentation.

**Describe the solution you'd like**

New images should be created, maybe marketing team could help with this?

**Comment by nikoheikkila** [comment]
Sounds good. I could add some rough sketches here which someone could polish if needed. 👍

**Comment by PaytrailTech** [comment]
https://paytraildocs.netlify.app/legacy/embedding/
Tuolla on kuva vanhasta Widgetistä, sen voisi ehkä päivittää tässä samassa yhteydessä.
