### ISSUE TITLE
E1/S1 description missing

### ISSUE THREAD

**Issue by PaytrailTech** [paytrail/documentation#25]
I was unable to find field-level description of the oleder form interfaces. They should be available for debuggin etc.

The contents can be found here: https://docs.paytrail.com/en/index-all-old.html

**Comment by nikoheikkila** [comment]
Yes, didn't bring these since they were marked as old. Not too hard to include these. The best place is perhaps under the legacy section.

**Comment by nikoheikkila** [comment]
We shall insert these in Other Interfaces and add a notice that E2 is preferred.
