### ISSUE TITLE
Add small introduction to the Payment creation-page

### ISSUE THREAD

**Issue by PaytrailTech** [paytrail/documentation#26]
Having a small intro to how payments are created with the FORM-interface and how the payment info ir relayed on this page:
https://paytraildocs.netlify.app/payments/

Would make the interface more approachable to first-time readers of the documentation. 
This page could contain image of the payment method selection page as well as a refreshed version of this image:
https://docs.paytrail.com/en/ch04s02.html#idm4814464208

Contents could be similar to this old section, but without the REST-mentions:
https://docs.paytrail.com/en/ch04.html#payment-api.intro

**Comment by nikoheikkila** [comment]
This can be added to page https://paytraildocs.netlify.app/payments/.

Example screenshot for the payment method selection can be added too.
