### ISSUE TITLE
Remove the deprecated payment method values from the documentation

### ISSUE THREAD

**Issue by PaytrailTech** [paytrail/documentation#28]
On this page:
https://paytraildocs.netlify.app/payment-methods/values/

The following values are deprecated and can be removed:
30 Visa
31 MasterCard
34 Diners Club
35 JCB

**Comment by PaytrailTech** [comment]
Question is if we should have a list of deprecated payment method values somewhere in the documentation? Would it be worth showing them so older implementations could be checked to see that they are no longer in use?

**Comment by nikoheikkila** [comment]
I second for another list to hold deprecated payment methods. We can have a warning block before those to make sure users understand it fully.
