### ISSUE TITLE
Improvements to Settlement details page

### ISSUE THREAD

**Issue by PaytrailTech** [paytrail/documentation#31]
This page:
https://paytraildocs.netlify.app/settlements/details/

1. Some of the data in thi table of the old documentation is not visible in the exapmple:
https://docs.paytrail.com/en/ch04s08.html#idm4813120944
For example datatype, occurrence, max length.

I personally like the way the example is built, so mayne this data can be commented into it?

2. In the Request example the settlement ID does not match the one in the example responce, would fix that to keep the example coherent.

3. Payer name explanation should be improved. Now says:
            // Payer name, only available for bank payments
Should be
            // Payer account owner's name from bank files, only available for bank payments

3. In the Payments-object -> payment id 176456276154 there is a refund with id DA2OTA4NWVmYTRiMDUyMWI4OGNkNjkxNzBh that is linked to settlementID 1234567. It is not mentioned in the Refunds-object, however, even though the id of the exapmle settlement is 1234567. I would recomment changing the settlement ID for this refund to make the example coherent.

4. rows[].amount kohdassa tieto maksimisummasta on väärin, lienee historian havinaa. Nykyinen max on 49999999.

**Comment by nikoheikkila** [comment]
This can be added as a sub-page to Settlements category. Research how to make it readable. Parameter listing should be consistent with other documentation.
