### ISSUE TITLE
Move Payment details-query from under MerchantAPI to under Settlements

### ISSUE THREAD

**Issue by PaytrailTech** [paytrail/documentation#41]
The Payment Details query in Merchant API is currently quite well hidden, but can be found here:
https://paytraildocs.netlify.app/merchant-api/v1/payments/

This shold be moved as a subpage to Settlements: 
https://paytraildocs.netlify.app/settlements/

So the links on the left would be:
    Listing Settlements
    Querying Settlement Details
    Querying Payment Details

**Comment by molsky** [comment]
Will be fixed in #39
