### ISSUE TITLE
Add refund flow sequence diagram to documentation

### ISSUE THREAD

**Issue by PaytrailTech** [paytrail/documentation#43]
This image:
https://docs.paytrail.com/images/refund_flow_sequence_diagram_en.png

Is missing from the documentation, should be on this page:
https://paytraildocs.netlify.app/refunds/notify/

I will allow for an update of the image if someone has the need for a prettier version of a sequence diagram :P

**Comment by nikoheikkila** [comment]
Support / Marketing researches if a better picture could be done. Current is good enough too.
