### ISSUE TITLE
Size of the refund status flow diagram

### ISSUE THREAD

**Issue by PaytrailTech** [paytrail/documentation#44]
The flow diagram here: https://paytraildocs.netlify.app/refunds/notify/

Is huge on my large screen, actually not completely visible without clicking the image or scrolling the screen. 

The image scales beaufifully, but can a max size be set?

**Comment by nikoheikkila** [comment]
Images stretch to full container width by default.

Hugo has a [shortcode](https://gohugo.io/content-management/shortcodes/#figure) available for presenting figures. It accepts more customization than standard Markdown. Could look into this, or alternatively reduce the image size on disk.
