### ISSUE TITLE
UI/UX issues with the current theme

### ISSUE THREAD

**Issue by nikoheikkila** [paytrail/documentation#56]
**Is your feature request related to a problem? Please describe.**

The current theme is a Git submodule from a 3rd party developer and cloned under the `themes/` subdirectory. Thus, it is not in our direct control.

This introduces a risk of the theme vanishing from GitHub, or the external maintainer doing potentially destructive changes. Fortunately, all the theme updates are run through CI tests so we can catch the errors early.

**Describe the solution you'd like**

This [theme repository](https://github.com/themefisher/dot) could be forked under our organization account and the `.gitmodules` in this project updated to reflect that.

Doing this would allow us to directly edit layouts, CSS, and JS code from this theme. As of now, I have spotted several stylistic issues we could improve:

- The font size of lists `<li>` is larger than the font size of paragraphs `<p>`
- Monospaced text is different pink (imported from Bootstrap CSS) to our official Paytrail pink
- Search box made with jQuery has some minor usability issues, and the search functionality could be improved a lot
- External libraries are stored as files in theme and lack consistent updates introducing minor security risks

**Alternatives**

We could also fix these by opening pull requests to the upstream repository, but I'm a sceptic towards that all of the Paytrail's wishes would be integrated there.

**Discussion is open!**

![Discuss](https://media.giphy.com/media/xT0xeOFWO8bCw68NgY/giphy.gif)

**Comment by Jipsukka** [comment]
Pull request #82 will break some HTML example blocks. We should make own fork sooner than later.
