### ISSUE TITLE
Final read-through comments

### ISSUE THREAD

**Issue by PaytrailTech** [paytrail/documentation#57]
https://paytraildocs.netlify.app/best-practices/requirements/
- Klarna requires the phone number for the customer. This has been mentioned in earlier documentation in  Table 4.10. Available payment method IDs
- Collector: please mention the exact PAYER_PERSON-fields, this is something we at technical customer service answer questions about all the time.

https://paytraildocs.netlify.app/payments/e2-interface/validation/
PAYER_PERSON_PHONE -> This field causes quite a few interface errors as people like to fill in their phone number in various ways at the checkout. Typical issue is with whitespace. Would it be possible to have a regExp here too? (fixed in #110)

https://paytraildocs.netlify.app/refunds/create/
- creating refunds with paymentID is not mentioned here at all, and should be in my opinion. Maybe a sub-page?

https://paytraildocs.netlify.app/settlements/payments-by-order-number/
Is the note on the interface not being available for the test merchant necessary here? The same info is given on the Settlements main page and is not mentioned on other sub-pages.

https://paytraildocs.netlify.app/legacy/migration/
Wondering if this content should be under Creating payments. Not a big concern though.

https://paytraildocs.netlify.app/legacy/e1-interface/ (fixed in #65)
Add link to creating payments to the tip.

https://paytraildocs.netlify.app/legacy/s1-interface/ (fixed in #65)
Add link to creating payments to the tip.

https://paytraildocs.netlify.app/legacy/rest-interface/
Sub-pages are in a wierd order, I would prefer the payment creation to be before errors if possible.

**Comment by nikoheikkila** [comment]
> Collector: please mention the exact PAYER_PERSON-fields, this is something we at technical customer service answer questions about all the time.

Mentioning all the fields in many places would add redundant lines. Should we link to E2 fields documentation from this page instead?

> PAYER_PERSON_PHONE -> This field causes quite a few interface errors as people like to fill in their phone number in various ways at the checkout. Typical issue is with whitespace. Would it be possible to have a regExp here too?

Yes. @laurasaari can probably find a regex for this one.

> Creating refunds with paymentID is not mentioned here at all, and should be in my opinion. Maybe a sub-page?

Turns out there was an issue #11 for this which was closed with PR #16 by accident, probably. I will reopen the issue.

> Is the note on the interface not being available for the test merchant necessary here? The same info is given on the Settlements main page and is not mentioned on other sub-pages.

I doubt it. It can be removed.
