### ISSUE TITLE
Documentation repo-link URL & encouragement to suggest corrections

### ISSUE THREAD

**Issue by kavakorh** [paytrail/documentation#60]
Dokumentaatio-sivulle voisi lisätä linkin repoon ja info-tekstin, että korjauksia voi ehdottaa jos löytyy virheitä / typoja yms.

Teksti voisi olla esim: "Dokumentaatiomme on avointa lähdekoodia, ja repo löytyy osoitteesta <https://github.com/paytrail/documentation/>. Jos löydät dokumentaatiostamme virheen, voit suoraan ehdottaa korjausta."

**Comment by nikoheikkila** [comment]
Dokumentaation yläpalkista löytyy _Changelog_ -linkki, joka vie tässä projektissa olevaan `CHANGELOG.md` -tiedostoon. Katsellaan pitäisikö sinne laittaa toinenkin linkki esim. tekstillä _GitHub_ tai _Source_.
