### ISSUE TITLE
Add info on email verification to creating refund

### ISSUE THREAD

**Issue by PaytrailTech** [paytrail/documentation#66]
https://docs.paytrail.com/refunds/create/
-> email
Should contain mention that the email address should be properly formatted.

Also add the error related to malformed email:

HTTP code: 400
Title: invalid-email
Description: Email address is malformed
Workaround: Check the email address

**Comment by nikoheikkila** [comment]
This is a good improvement. I'll see what regex we use for that validation and add that.
