### ISSUE TITLE
Contradictory information in documentation

### ISSUE THREAD

**Issue by oskarolaussen** [paytrail/documentation#70]
**Describe the bug**
Documentation has contradictory information on if ITEM_UNIT_PRICE may or may not be negative.

On https://docs.paytrail.com/payments/e2-interface/fields/

"ITEM_UNIT_PRICE[N] (*)

The price for a single product with up to two decimals.

If VAT_IS_INCLUDED = 0, this is price excluding VAT. Price may be negative value if discount is given."

On https://docs.paytrail.com/payments/e2-interface/validation/

"ITEM_UNIT_PRICE

Floating point number. between 0–499 999.99. (10)"

**Additional context**

I would also be interested to know if there have been a change to the validation resently? The interface doesn't seem to accept negative values for ITEM_UNIT_PRICE but I'm fairly certain that it did before. Please correct me if I'm wrong.

**Comment by PaytrailTech** [comment]
Single Item row can have a negative ITEM_UNIT_PRICE as long as the payment total is at least 0,65€. The description should be fixed.

**Comment by PaytrailTech** [comment]
Also ITEM_QUANTITY should be given on all rows if any of the rows have a negative ITEM_UNIT_PRICE. Maybe this could even be documented as something like:
ITEM_ -rows should have similar content on all rows; if ITEM_QUANTITY is given on one row it is recommended it be given for all rows.
