### ISSUE TITLE
Payment method ids 11 and 12 should be marked as deprecated

### ISSUE THREAD

**Issue by laurasaari** [paytrail/documentation#86]
**Is your feature request related to a problem? Please describe.**

Payment method ids 11 and 12 will be removed by 10/2020 and those should be marked as deprecated here https://docs.paytrail.com/payment-methods/values/ and removed from here https://docs.paytrail.com/best-practices/requirements/

**Comment by Jipsukka** [comment]
There's also mention about Klarna inside text fields in couple of places, those should be removed as well when marking payment methods as deprecated.
